# Generated by Django 5.0 on 2024-01-02 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('EmailAddress', models.CharField(max_length=50)),
                ('ContactNumber', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter in +9666666699.Upto 15 digits', regex='^\\+?1?\\d{9,15}$')])),
                ('HomeAddress', models.TextField(blank=True, default='')),
                ('Birthday', models.DateField(blank=True, default='', null=True)),
                ('Nickname', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
